### ISSUE TITLE
Illegal Logseq plugin package.what's wrong?

### ISSUE THREAD

**Issue by 20130216** [briansunter/logseq-plugin-gpt3-openai#140]
I followed your instructions exactly:

First run `npm i` and `npm run build`

In logseq load the plugin folder dist from the package.json file above using the npm run build command,

Install the plugin for local logseq by loading the dist folder.

The following error alerts occur:

instrument.js:191 ERROR: [PluginLocal][19:46:11] loadParse package config error #/Users/wingzheng/Desktop/github/logseq-zotero/logseq-plugin-gpt3-openai/dist/package.json IllegalPluginPackageError: Parse package config error #/Users/wingzheng/Desktop/github/logseq-zotero/logseq-plugin-gpt3-openai/dist/package.json
    at br._preparePackageConfigs (file:///Applications/Logseq.app/Contents/Resources/app/js/lsplugin.core.js:2:94927)
    at async br.load (file:///Applications/Logseq.app/Contents/Resources/app/js/lsplugin.core.js:2:98913)
    at async vr.register (file:///Applications/Logseq.app/Contents/Resources/app/js/lsplugin.core.js:2:103590)
    at async vr.register (file:///Applications/Logseq.app/Contents/Resources/app/js/lsplugin.core.js:2:102645)

Also remind：

**Illegal Logseq plugin package.**

What went wrong after a day of incomprehension?

**Comment by briansunter** [comment]
I updated the instructions to use pnpm, could you try that?
