### ISSUE TITLE
takes too long to load, affecting the application startup time and potentially causing other plugins to fail to load.

### ISSUE THREAD

**Issue by 20130216** [briansunter/logseq-plugin-gpt3-openai#141]
- I to git clone https://github.com/briansunter/logseq-plugin-gpt3-openai this latest version, according to its alert again to compile, Then put the latest dist folder under the plugins package logseq-plugin-gpT3-openai and restart logseq, but it still appears: This plugin #logseq-plugin-gpt3-openai takes too long to load, affecting the application startup time and potentially causing other plugins to fail to load. This is completely compiled according to the latest official version of logseq-plugin-gpt3-openai, is it because I changed the logseq-plugin-gpt3-openai version retained some Settings, so that even if I compile with a new version, this problem still occurs? The reminder in the console is:
-
- logseq-omnivore starting sync since: '2024-09-17T21:35:29
  54index.7a96a8a6.js:2 console.log event added  
  instrument.js:191 :shortcut/register-shortcut [:shortcut.handler/editor-global :plugin.logseq-wrap/repl-clear {:fn #object[Function], :desc nil, :key repl-clear, :type $palette$ , :binding (meta+shift+x), :label unformat, :cmd {:id :plugin.logseq-wrap/repl-clear, :desc unformat, :shortcut mod+shift+x, :handler-id :shortcut.handler/editor-global, :action #object[Function]}, :keybinding {:binding mod+shift+x}, :extras nil}]  
  2index.7a96a8a6.js:2 console.log event added  
  instrument.js:191 db restored, setting up repo hooks  
  92index.7a96a8a6.js:2 console.log event added  
  instrument.js:191 :frontend.fs.watcher-handler/preload-homepage "journals/2024_09_17.md"  
  72index.7a96a8a6.js:2 console.log event added  
  api.github.com/repos/pengx17/logseq-dev-theme/releases?per_page=1:1   
  
  
         Failed to load resource: the server responded with a status of 403 ()  
  api.github.com/repos/pengx17/logseq-dev-theme/releases?per_page=1:1   
  
  
         Failed to load resource: the server responded with a status of 403 ()  
  api.github.com/repos/pengx17/logseq-dev-theme/releases?per_page=1:1   
  
  
         Failed to load resource: the server responded with a status of 403 ()  
  api.github.com/repos/pengx17/logseq-dev-theme/releases?per_page=1:1   
  
  
         Failed to load resource: the server responded with a status of 403 ()  
  api.github.com/repos/pengx17/logseq-dev-theme/releases?per_page=1:1   
  
  
         Failed to load resource: the server responded with a status of 403 ()  
  api.github.com/repos/pengx17/logseq-dev-theme/releases?per_page=1:1   
  
  
         Failed to load resource: the server responded with a status of 403 ()  
  api.github.com/repos/pengx17/logseq-dev-theme/releases?per_page=1:1   
  
  
         Failed to load resource: the server responded with a status of 403 ()  
  api.github.com/repos/pengx17/logseq-dev-theme/releases?per_page=1:1   
  
  
         Failed to load resource: the server responded with a status of 403 ()  
  index.ce0c572c.js:12 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'name')  
      at ru (index.ce0c572c.js:12:80693)  
      at async Mn.iu (index.ce0c572c.js:13:180)  
  20index.7a96a8a6.js:2 console.log event added  
  instrument.js:191 :frontend.fs.watcher-handler/initial-watcher "/Users/wingzheng/Desktop/github/logseq-zotero/logseq/AI-PPT" {:deleted 0, :total 139}  
  index.7a96a8a6.js:2 console.log event added  
  instrument.js:191 reloading custom.css  
  2index.7a96a8a6.js:2 console.log event added  
  index-0a1bc9c3.js:224 reset loading state  
  27index.7a96a8a6.js:2 console.log event added  
  index.7a96a8a6.js:2 console.log event added

**Comment by briansunter** [comment]
Sounds like you're trying to build it locally and run it. You should just have to run `pnpm i` , `pnpm run build` then open the `Load unpacked plugin` option in the marketplace, and select the `logseq-plugin-gpt3-openai` folder (not just the dist folder). Let me know if that works or fixes it. I tried it locally and it seems to be working for me.
